# Generated by Django 5.0.6 on 2024-07-03 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_department_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='info.employee'),
        ),
    ]
